const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const out = __dirname;
const root = path.resolve(__dirname, '../..');
const loaderSource = fs.readFileSync(path.join(root, 'assets/js/logo-loader.js'), 'utf8');
const siteSource = fs.readFileSync(path.join(root, 'assets/js/site.js'), 'utf8');
const results = [];

class Events {
  constructor() { this.listeners = new Map(); }
  addEventListener(type, fn, options = {}) { const a=this.listeners.get(type)||[]; a.push({fn,once:options.once});this.listeners.set(type,a); }
  removeEventListener(type,fn){this.listeners.set(type,(this.listeners.get(type)||[]).filter(e=>e.fn!==fn));}
  dispatch(type, properties={}) { const e={type,target:this,preventDefault(){this.defaultPrevented=true;},...properties}; for(const entry of [...(this.listeners.get(type)||[])]){if(entry.once)this.removeEventListener(type,entry.fn);entry.fn(e);}return e; }
}
class Element extends Events {
  constructor(tag='div') { super();this.localName=tag;this.tagName=tag.toUpperCase();this.attrs={};this.children=[];this.dataset={};this.hidden=false;this.textContent='';this.selectorMap={};const classes=new Set();this.classList={add:(...s)=>s.forEach(x=>classes.add(x)),remove:(...s)=>s.forEach(x=>classes.delete(x)),contains:x=>classes.has(x)}; }
  appendChild(node){this.children.push(node);node.parentNode=this;node.parentElement=this;return node;}
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);this.parentNode=null;}
  setAttribute(k,v){this.attrs[k]=String(v);}
  getAttribute(k){return this.attrs[k]??null;}
  querySelector(selector){return this.selectorMap[selector]??null;}
  querySelectorAll(selector){return this.selectorMap[selector]??[];}
  closest(selector){return this.closestMap?.[selector]??null;}
  reportValidity(){return this.valid!==false;}
  focus(){this.focused=true;}
  select(){this.selected=true;}
}
function environment({critical=[],form=false,video=false,clipboard=false,readyState='complete',reducedMotion=false}={}) {
  const document=new Events();document.body=new Element('body');document.documentElement={lang:'en'};document.readyState=readyState;document.hidden=false;document.createElement=t=>new Element(t);document.createElementNS=(_,t)=>new Element(t);
  const all={};document.querySelector=s=>all[s]??null;document.querySelectorAll=s=>s.startsWith('.brand img')?critical:(all[s]??[]);
  const window=new Events();let now=0,id=0;const scheduled=new Map();
  window.setTimeout=(fn,delay=0)=>{const n=++id;scheduled.set(n,{fn,due:now+delay,kind:'timer'});return n;};window.clearTimeout=n=>scheduled.delete(n);
  window.requestAnimationFrame=fn=>{const n=++id;scheduled.set(n,{fn:()=>fn(now),due:now+16,kind:'raf'});return n;};window.cancelAnimationFrame=n=>scheduled.delete(n);
  const media=new Events();media.matches=reducedMotion;window.matchMedia=()=>media;
  const advance=ms=>{const end=now+ms;let loops=0;while(true){const entries=[...scheduled.entries()].filter(([,v])=>v.due<=end).sort((a,b)=>a[1].due-b[1].due);if(!entries.length)break;const [key,event]=entries[0];scheduled.delete(key);now=event.due;event.fn();assert(++loops<20000,'unbounded callback loop');}now=end;};
  const navigator={};const controls={};
  if(clipboard){controls.brief=new Element('textarea');controls.brief.value='PLMR brief';controls.copy=new Element('button');controls.copy.disabled=false;const target=new Element();target.appendChild(controls.copy);document.body.appendChild(target);controls.copyStatus=new Element();Object.assign(all,{'[data-project-brief]':controls.brief,'[data-copy-brief]':controls.copy,'[data-copy-status]':controls.copyStatus});navigator.clipboard={writeText:()=>Promise.resolve()};}
  if(video){controls.video=new Element('video');controls.video.paused=true;controls.video.ended=false;controls.video.readyState=0;controls.video.error=null;controls.figure=new Element('figure');controls.video.closestMap={'.software-demo':controls.figure};document.body.appendChild(controls.figure);controls.figure.appendChild(controls.video);all['.software-video']=[controls.video];}
  if(form){controls.form=new Element('form');controls.form.action='/api/contact';controls.form.fields={name:'QA',email:'qa@example.com',country:'Test',helpType:'Engineering / Technical Review',message:'Fixture only',consent:'yes'};controls.form.reset=()=>{controls.form.resetCount=(controls.form.resetCount||0)+1;};document.body.appendChild(controls.form);for(const [key,selector] of Object.entries({submit:'[data-contact-submit]',status:'[data-contact-status]',fallback:'[data-contact-fallback]',fallbackLink:'[data-contact-email-fallback]',images:'[data-project-images]',imageSummary:'[data-image-summary]'})){const el=new Element(key==='submit'?'button':'div');controls[key]=el;controls.form.selectorMap[selector]=el;controls.form.appendChild(el);}controls.images.files=[];controls.submit.textContent='Send Project Details';controls.submit.disabled=true;controls.fallback.hidden=true;all['[data-contact-form]']=controls.form;}
  const errors=[];const context=vm.createContext({window,document,navigator,performance:{now:()=>now},console:{warn:(...x)=>errors.push(x.map(String).join(' '))},IntersectionObserver:undefined,AbortController,URLSearchParams,FormData:class{constructor(el){this.el=el;}get(name){return this.el.fields[name]||'';}},fetch:(...args)=>controls.fetch(...args),setTimeout:window.setTimeout,clearTimeout:window.clearTimeout});window.location={search:''};
  vm.runInContext(loaderSource,context);
  const walk=(el,tag)=>el.children.flatMap(c=>[...(tag&&c.tagName===tag.toUpperCase()?[c]:[]),...walk(c,tag)]);
  const views=()=>{const list=[];const visit=el=>{if(el.className?.startsWith('plmr-loader '))list.push(el);el.children.forEach(visit);};visit(document.body);return list;};
  const svg=()=>views()[0]?.children[0];
  return {window,document,context,advance,scheduled,controls,errors,media,views,walk,svg,loadSite:()=>vm.runInContext(siteSource,context)};
}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function serialization(el){const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');const tag=el.localName||el.tagName.toLowerCase();return `<${tag}${Object.entries(el.attrs).map(([k,v])=>` ${k}="${esc(v)}"`).join('')}>${esc(el.textContent)}${el.children.map(serialization).join('')}</${tag}>`;}
function saveSVG(e,name){let s=serialization(e.svg());s=s.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" ');const png=fs.readFileSync(path.join(root, 'assets/img/plmr-logo-primary.png')).toString('base64');s=s.replaceAll('/assets/img/plmr-logo-primary.png','data:image/png;base64,'+png);fs.writeFileSync(path.join(out,name+'.svg'),s);}
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(error){results.push({name,status:'FAIL',message:error.message});console.error('FAIL',name,error.stack);}}

module.exports={environment,saveSVG};
if(require.main===module)(async()=>{
 await test('Short load never becomes visible; end clears all decorative work',()=>{const e=environment();const t=e.window.PLMRLoading.begin();e.advance(180);assert(e.views()[0].hidden);t.end();assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);});
 await test('Original bitmap first, continuous morph after 1 second, rider after morph',()=>{const e=environment();const t=e.window.PLMRLoading.begin();e.advance(500);assert.equal(e.views()[0].hidden,false);assert.equal(e.svg().children[0].children[0].attrs.opacity,'1');saveSVG(e,'01-original');e.advance(750);const morph=e.svg().children[0].children[1].children.at(-1).attrs.d;saveSVG(e,'02-morph');e.advance(350);assert.notEqual(morph,e.svg().children[0].children[1].children.at(-1).attrs.d);e.advance(300);saveSVG(e,'03-waiting');assert(!e.views()[0].children[1].textContent.includes('%'));t.end();assert.equal(e.scheduled.size,0);});
 await test('Measured 0-100 route; stalled progress freezes wheels and pedals without RAF',()=>{const e=environment();const t=e.window.PLMRLoading.begin();t.update(0,100);e.advance(1900);const rider=e.svg().children.at(-1);assert.equal(rider.dataset.progress,'0');for(const progress of [0,25,50,75,100]){t.update(progress,100);assert.equal(rider.dataset.progress,String(progress/100));saveSVG(e,'progress-'+progress);const transform=rider.attrs.transform;const pedal=e.walk(rider,'path').at(-1).attrs.d;e.advance(500);assert.equal(rider.attrs.transform,transform);assert.equal(e.walk(rider,'path').at(-1).attrs.d,pedal);assert.equal(e.scheduled.size,0);}t.end();assert.equal(e.views().length,0);});
 await test('Measured movement also moves pedals; invalid totals do not create false percentages',()=>{const e=environment();const t=e.window.PLMRLoading.begin();t.update(0,0);e.advance(1900);assert(!e.views()[0].children[1].textContent.includes('%'));t.update(20,100);const rider=e.svg().children.at(-1),p=e.walk(rider,'path').at(-1).attrs.d;t.update(25,100);assert.notEqual(e.walk(rider,'path').at(-1).attrs.d,p);t.end();});
 await test('Completion is immediate and does not impose a minimum display duration',()=>{const e=environment();const t=e.window.PLMRLoading.begin();e.advance(245);assert(!e.views()[0].hidden);t.end();assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);});
 await test('Background tab stops all decorative timers and frames; resume and reset are safe',()=>{const e=environment();const t=e.window.PLMRLoading.begin();e.advance(2000);e.document.hidden=true;e.document.dispatch('visibilitychange');assert.equal(e.scheduled.size,0);e.advance(10000);e.document.hidden=false;e.document.dispatch('visibilitychange');assert(e.scheduled.size>0);e.window.dispatch('pagehide');assert.equal(e.scheduled.size,0);assert.equal(e.views().length,0);e.window.dispatch('pageshow',{persisted:true});t.end();});
 await test('Reduced motion leaves original logo and text with no bicycle or animation work',()=>{const e=environment({reducedMotion:true});const t=e.window.PLMRLoading.begin();e.advance(2500);assert.equal(e.scheduled.size,0);assert.equal(e.svg().children[0].children[0].attrs.opacity,'1');assert.equal(e.svg().children.at(-1).attrs.opacity,'0');saveSVG(e,'04-reduced');t.end();});
 await test('Rapid navigations/back-forward lifecycle and concurrent tasks never leave stale indicators',()=>{const e=environment();for(let i=0;i<10;i++){const first=e.window.PLMRLoading.begin();e.advance(80);const second=e.window.PLMRLoading.begin();assert.equal(e.views().length,1);first.end();assert.equal(e.views().length,1);e.advance(1900);e.window.dispatch('pagehide');e.window.dispatch('pageshow',{persisted:true});second.end();assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);}});
 await test('Visible critical startup image resolves or fails without waiting for background media',()=>{const img=new Element('img');img.complete=false;const e=environment({critical:[img],readyState:'interactive'});e.advance(2000);assert.equal(e.views().length,1);img.dispatch('error');assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);});
 await test('Stuck startup image has a 15-second nonblocking fail-safe and removes image listeners',()=>{const img=new Element('img');img.complete=false;const e=environment({critical:[img],readyState:'interactive'});e.advance(15001);assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);assert.equal(img.listeners.get('load').length,0);});
 await test('Form success/error preserve existing feedback and re-enable retry; no real message is sent',async()=>{for(const success of [true,false]){const e=environment({form:true});let settle;e.controls.fetch=()=>new Promise(resolve=>{settle=resolve;});e.loadSite();e.controls.form.dispatch('submit');e.advance(1900);assert(e.controls.submit.disabled);assert.equal(e.views().length,1);settle({ok:success,status:success?200:503,headers:{get:()=> 'application/json'},json:async()=>({success})});await flush();assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);assert.equal(e.controls.submit.disabled,false);if(success)assert(e.controls.status.textContent.includes('sent.'));else{assert.equal(e.controls.fallback.hidden,false);assert(e.controls.fallbackLink.href.startsWith('mailto:'));}}});
 await test('Form connection failure and 45-second abort remove loader and keep fallback/retry',async()=>{for(const timeout of [false,true]){const e=environment({form:true});let reject;e.controls.fetch=(_,options)=>new Promise((_,r)=>{reject=r;options.signal.addEventListener('abort',()=>r(new Error('aborted')));});e.loadSite();e.controls.form.dispatch('submit');e.advance(timeout?45001:1900);if(!timeout)reject(new Error('fixture network failure'));await flush();assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);assert(!e.controls.submit.disabled);assert(!e.controls.fallback.hidden);if(timeout)assert(e.controls.status.textContent.includes('Delivery could not be confirmed'));}});
 await test('Clipboard success and timeout cleanup, including selected-text fallback',async()=>{for(const timeout of [false,true]){const e=environment({clipboard:true});if(timeout)e.context.navigator.clipboard.writeText=()=>new Promise(()=>{});e.loadSite();e.controls.copy.dispatch('click');e.advance(timeout?8001:1900);await flush();assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);assert(!e.controls.copy.disabled);assert(timeout?e.controls.brief.selected:e.controls.copyStatus.textContent.includes('copied'));}});
 await test('Video metadata and pause stay quiet; real playback waits locally, ends on playing/error',()=>{const e=environment({video:true});e.loadSite();const v=e.controls.video;v.dispatch('stalled');e.advance(2000);assert.equal(e.views().length,0);v.paused=false;v.dispatch('waiting');e.advance(2000);assert.equal(e.views().length,1);assert.equal(e.views()[0].className,'plmr-loader plmr-loader--media');saveSVG(e,'05-media');v.readyState=3;v.dispatch('playing');assert.equal(e.views().length,0);v.readyState=1;v.dispatch('waiting');e.advance(250);v.error={code:3};v.dispatch('error');assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);});
 await test('Failed video buffering stops decorative animation after 30 seconds; native player stays intact',()=>{const e=environment({video:true});e.loadSite();const v=e.controls.video;v.paused=false;v.dispatch('waiting');e.advance(30001);assert.equal(e.views().length,0);assert.equal(e.scheduled.size,0);v.dispatch('stalled');e.advance(2000);assert.equal(e.views().length,0);});
 await test('Loading component failure is isolated from contact delivery and site initialization',async()=>{const e=environment({form:true});e.window.PLMRLoading={begin(){throw new Error('fixture component unavailable');}};e.controls.fetch=async()=>({ok:true,status:200,headers:{get:()=> 'application/json'},json:async()=>({success:true})});e.loadSite();e.controls.form.dispatch('submit');await flush();assert.equal(e.controls.submit.disabled,false);assert(e.controls.status.textContent.includes('sent.'));assert.equal(e.views().length,0);});
 fs.writeFileSync(path.join(out,'behavior-results.json'),JSON.stringify({method:'Node VM, deterministic time and DOM/event fixtures; no live email or browser navigation',results},null,2));
 if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})();
